### ISSUE TITLE
propagative versus non propagative transmission

### ISSUE THREAD

**Issue by PhiBabs935** [infectious-disease-ontology-extensions/ido-core#13]
From Cahn _Principles of Molecular Virology_ (p. 175): "Insects that bite or suck plant tissues are the ideal means of transmitting viruses to new hosts—a process known as nonpropagative transmission. However, in other cases (e.g., many plant rhabdoviruses), the virus may also infect and multiply in the tissues of the insect (propagative transmission) as well as those of host plants. In these cases, the vector serves as a means not only of distributing the virus but also of amplifying the infection."

Something we discussed previously. There didn't seem to be coverage of these in any ontologies.

I would note that the label Cahn uses, non propagative transmission, seems odd given the description. Why the label's emphasis on not having to do with propagation when it seems that the essence of the process is that it involves an insect bite? 

I double-checked TRANS:

Would what Cahn calls non propagative be captured by the following TRANS term?
_vector borne bite_ =def Vector-borne bite transmission is an indirect vector-borne transmission during which the pathogen is indirectly transferred by insect bites from a reservoir, source or host via a vector to another host.

There is no class that captures propagative transmission. But I assume that it would, once added to TRANS, be a subclass of:

_vector-borne gastro-intestinal_ =def Vector-borne gastro-intestinal transmission is an indirect vector-borne transmission process during which the pathogen is transported, from a reservoir, source or host to another host, within the vector and undergoes part of it's lifecycle in the intermediate host.

John, you had mentioned that propagative is a species of biologic transmission, and _vector-borne gastro-intestinal_ is asserted to have exact synonym biologic transmission. 

At some point I will have to put in a term request with TRANS.

**Comment by lschriml** [comment]
Propagative transmission added to TRANS

Cheers,
Lynn Schriml

**Comment by PhiBabs935** [comment]
Thanks for this!
