### ISSUE TITLE
Establishment of localization in host

### ISSUE THREAD

**Issue by PhiBabs935** [infectious-disease-ontology-extensions/ido-core#16]
I was in the process of addressing a comment from Werner (from the IDO paper) concerning this class, and a related issue arose that pertains to our new IDO classification of viruses. So I thought it would warrant a separate issue.

_Establishment of localization in host_ =def Establishment of localization process in which a material entity reaches a site in an organism in which it can survive, grow, multiply, or mature. 
(this serves as a parent for IDO: _colonization of host_

Werner objected that this term is too broad on the grounds that it would apply to the case of putting on a hat, using a sanitary tampon, or the case of a child in the womb.

For the tampon case, he argued that depending on what we mean by "grow", the insertion of a tampon would count in the sense that it reaches a site where it can grow as a result of soaking up blood. Now, I think that it's obvious that we mean "grow" in a biological sense, so I am kind of at a loss for words as to what he expects from us here. Is he suggesting that every textual definition has to be explicit as possible so as to rule out even interpretations that are obviously not intended given the context? I think it's obvious that in the context of defining a class which is derived from classes from the biological process branch of the Gene Ontology (GO) it can be assumed what we mean by "grow" here. I guess we could add "in the biological sense", but it seems that any rule that requires such clarifications would be an overly excessive constraint on textual definitions. (Though, to be fair we didn't mention in the paper the GO terms that _establishment of localization in host_ derives from.)

He didn't give an example to justify the hat case, but the same points as above would apply here.

That said, this response doesn't address the child in the womb case. Nevertheless, I think all the cases can be handled once we look more carefully at the GO classes that this IDO term descends from.

In IDO, _establishment of localization in host_ is a child of the GO class _establishment of localization_, defined as “Any process that localizes a substance or cellular component. This may occur via movement, tethering or selective degradation.” This in turn is a child of the GO class _localization_ defined as “Any process in which a cell, a substance, or cellular entity, such as a protein complex or organelle, is transported, tethered to or otherwise maintained in a specific location. In the case of a substances, localization may also be achieved via selective degradation.” 

To be fair, we didn't mention these classes in the paper, and the _localization_ class is not imported in IDO. I think that we should import it just to make absolutely clear what features _establishment of localization in host_ inherits from it.

Given the GO term it descends from, _establishment of localization in host_ is restricted to cells, substances and cellular entities (meaning components), and that’s it would not apply to the cases Werner discusses. Rather it is correctly restricted to things like cells -- such as unicellular pathogens like bacteria and unicellular eukaryotic parasites -- and cell components like proteins, as in the case of prions. 

Now, I am not exactly sure what GO is referring to by 'substances' here, but I assume that it doesn't include the macro-entities Werner discusses.

I think that addresses Werner's worry, what do people think?

That said, having investigated the GO classes further, I now think there is another important issue we need to think about. It has to do with our new classification of viruses as a acellular structures. _Establishment of localization in host_ also is supposed to apply to viruses. But do this term apply to them, as it is currently defined? Viruses are not cells, and they are not cellular components. So, it would only apply to viruses if they fall under what GO refers to as substances. 

Any thoughts? If viruses do not fall under these GO terms so defined, we may need to ask the GO consortium to adjust these terms so that they also mention acellular structures.

One last problem though: 

notice that GO: _establishment of localization_ only mentions in its definition substances and cellular components. I wonder whether this is what they intended? Was it only supposed to apply to substances and cellular components, and not cells? If so then the IDO term _establishment of localization in host_ is problematic. If it applies to cells (bacteria, unicellular eukaryotic parasites) then it would not be correct to have it be a child of the GO term, assuming that only applies to substances and cell components. I will also confer with Alex Diehl on these matters.

**Comment by johnbeve** [comment]
I agree Werner's concerns are addressed. But he should've done his homework; it would've been less work for him to google the relevant GO terms than to write an unfounded diatribe email.

I think the GO term mentioning of substances and cellular components is meant to emphasize these are the means by which entities attach to other entities. But that doesn't preclude viruses, bacteria, etc. from being involved in establishing localization. SARS-CoV-2 establishes itself on a host respiratory cell through (S) protein binding to ACE2 receptors, the former present on the virus surface and the latter on a cellular membrane. Put another way, when we're saying a virus participates in an establishment of localization in host process, I'm reading that as sets of relevant protein component parts of the virus and host linking to each other. 

Related, I'm wondering why establishment in the definition is in an 'organism' and not in a 'host'.

**Comment by PhiBabs935** [comment]
Ah I see. That makes sense, but it wasn't clear to me from the GO definitions. This can perhaps be clarified briefly in a term comment. 

Will think about the last issue you raised.

**Comment by PhiBabs935** [comment]
"Tethering" refers to a specific biological process involving "tethers" (see: https://en.wikipedia.org/wiki/Tether_(cell_biology)#:~:text=Biological%20cells%20which%20form%20bonds,main%20body%20of%20the%20cell.) Do you think that these are distinct from the cell receptors in the case of pathogen proteins binding to cell receptors? If yes, I am assume protein-cell receptor binding would fall under the "or otherwise maintained in a specific location" clause of _localization_? Just asking because I am trying to be as specific as possible in my reply to Werner's comment when I invoke the GO terms.

**Comment by PhiBabs935** [comment]
As for your question. It doesn't seem like there would be anything wrong with saying 'host' rather than 'organism'. 

The OWL definition is: 'establishment of localization' and ('occurs in' some host), so I don't see why they wouldn't put host in the textual definition. Once Alex replies to the last email I sent him, I will ask him if there is any rationale for the choice of 'organism'.

**Comment by PhiBabs935** [comment]
Looks like we settled these issues
