### ISSUE TITLE
Pathogenic disposition and infectious disposition

### ISSUE THREAD

**Issue by PhiBabs935** [infectious-disease-ontology-extensions/ido-core#18]
pathogenic disposition =def Disposition to initiate processes that result in a disorder.

Werner has objected (paraphrasing): This is way to general. It would count toxins and poisons as pathogens. It would also count humans as pathogens, because while driving a car I can initiate a collision with another human being that results in that person having a head fracture.

Reply: the point about toxins and poisons is answered by an editor's comment for the term: "The use of 'initiates' is intended to convey that a pathogenic disposition is realized when processes resulting in a disorder begin because of some action on the part of the bearer of the disposition. By this interpretation of 'initiates', disorder-causing entities such as glass, UV light, and toxins do not have a pathogenic disposition." (i.e., when _clostridium botulinum_ produces toxins that in turn cause botulism, it is the bacteria that initiated the process, not the toxin).

Unfortunately, this doesn't help with the human being case, because the human is clearly initiating the process leading to a disorder.

But I think we can fix up pathogenic disposition by adding that pathogens are disposed to undergo establishment of localization in a host. Thus something like:

pathogenic disposition =def Disposition that inheres in a material entity and is a disposition for that material entity to establish itself in a host and initiate processes that result in a disorder.

For instance, take _clostridium botulinum_ , which bears a pathogenic disposition, but not an infectious disposition. It can initiate processes leading to the illness _infant botulism_ when the bacteria colonizes (which is a type of establishment of localization) the small intestines of an infant early in their life (https://en.wikipedia.org/wiki/Botulism#Colonization_of_the_gut). So, it seems that the pathogenic disposition involves a disposition to establish in the host.

Adding the reference to _establishment of localization in host_ rules out the human being case since the GO superclass localization is sufficiently restricted to processes at the cellular level, as we discussed in issue #16 
-this also emphasizes the point that pathogens can use hosts to survive, grow, multiply and mature.

The only problem though is that now I am worried again about the distinction between _pathogenic disposition_ and _infectious disposition_. 
 There is clearly a difference between being a pathogen and being an infectious entity, as we discussed in issue #12 with respect to the non-infectious pathogen _clostridium botulinum_. This pathogen is not able to infect a host, but can be transmitted instead via ingestion of food contaminated by the pathogen.

The issue is that I don't clearly see how this difference is reflected properly in the IDO definitions.

infectious disposition =def A pathogenic disposition that inheres in an organism or acellular structure and is a disposition for that entity (1) to be transmitted to a host, (2) to establish itself in the host, (3) to initiate processes that result in a disorder in the host, and (4) to become part of that disorder.

_clostridium botulinum_ seems to be disposed towards all of 1-3. Maybe not 4), I am not sure about that one. It initiates processes leading to disorder by producing toxins that in turn cause a disorder in the host, as in the case of infant botulism, but I guess the bacteria itself doesn't become part of the disorder?? 
-That said it doesn't seem like _clostridium botulinum_'s not being infectious is essentially about it's failing to satisfy 4, but rather about it's inability to infect an organism. (?)

Can we perhaps fix this by adding to 'infectious disposition' a clause the refers to 'process of establishing an infection'? After all, establishment of localization in a host need not establish an infection.

**Comment by PhiBabs935** [comment]
I think the suggested fix at the end of my post is in line with 'process of establishing an infection', which is the process by which something becomes part of an infection after establishing itself in the host. _clostridium botulinum_ is disposed to establish itself in the host, but not disposed to become part of an infection in the host. So the disposition to establish an infection in the host is what it is missing, so that should be in the definition of 'infectious disposition'. Once it is localized, it just causes disorder through the toxins it produces.

**Comment by PhiBabs935** [comment]
I guess that _infectious disposition_ clause 4) is supposed to cover an infectious entity's becoming part of an infection. But since we distinguish infection from infectious disorder, becoming part of a disorder is not the same as becoming part of an infection. Our current definition for _infectious disposition_ does not account for the case in which an HIV virus would partially realize its infectious disposition insofar that it establishes an infection in a host, but fails to initiate a disorder if that host is resistant due to a mutation of the CCR5 gene.

**Comment by johnbeve** [comment]
I think I've a way to rework this so it covers what we need and avoids the concerns raised. Let's talk it out today if you're free, and if you like where I'm headed, I'll post it here and update the files. It's basically in line with what you're saying and what we've discussed elsewhere about processes, just nailing the details down precisely.

**Comment by PhiBabs935** [comment]
Sounds good to me! Just let me know when you are free.

**Comment by PhiBabs935** [comment]
Let's talk about the dropping of disorder-formation from the definition of infectious disposition at today's call. I still think I need to be shown has these issues are addressed.

**Comment by johnbeve** [comment]
I didn't mean to drop it entirely, it's supposed to be entailed by
infectious disposition being a pathogen disposition, and pathogen
disposition being realized in an appearance of disorder, and appearance of
disorder defined as being a process resulting in a disorder.

**Comment by PhiBabs935** [comment]
Ah, of course, that makes sense. I see now why you phrased pathogenic disposition the way you did!
