### ISSUE TITLE
pathogen/infectious agent transporter role

### ISSUE THREAD

**Issue by PhiBabs935** [infectious-disease-ontology-extensions/ido-core#19]
Hopefully the last issue I will be posting for a bit.

infectious agent transporter role =def. Role borne by a material entity in virtue of the fact that an infectious agent is located in or on the entity and the entity has the capability to transfer (either actively or passively) the infectious agent from one location to another.  

It has been pointed out that this definition is too wide, because the "from one location to another" clause doesn't specify the end-point location precisely enough. This role's OWL axiom has a clause specifying that it is realized in only indirect pathogen transmission processes. And pathogen transmission processes by definition conclude with the pathogen ending up in a new host.

But as currently worded, a petri dish with cultured bacteria moved from one location to another (say on the table) counts as a realization of this role, which shouldn't be allowed. Of course, there may be some contexts where bacteria culture medium might realize the fomite role (such as when the bacteria culture medium is rubbed into an open skin wound perhaps), but not all contexts. 

I suggest simply changing the last phrase to "from one location to a new host". Leaving "location" here allows for realizations of the role where a pathogen is transported from a non-organism pathogen _reservoir_ to a host.

One other issue though. There is a debate as to whether some of the roles descending from this class should instead be re-classified as dispositions. I think one of its subclasses, "pathogen vehicle role", and its two children, are fine staying as roles. But perhaps that can be argued too? Do respiratory droplets have a disposition to transfer viruses? Or should this be a role?

The problem case is the subclass "pathogen vector role". One could argue that vector's have a disposition to transport pathogen's that is based in their physical structure.

And a final note: _pathogen transporter role_ refers to a 'capability' of the material entity to transfer a pathogen. But if 'capability' can be read as a disposition (which is certainly how BFO people use it in many contexts) then by this definition a material entity has a role (externally grounded entity) in virtue of having a disposition (which is internally grounded). Is that an issue? What do people think?

**Comment by PhiBabs935** [comment]
Now that I think about it, the last thing I said may not be a worry at all. The role is externally grounded to the extent that the bearing of the role depends on an external factor--an infectious agent being located on the transporter entity. Can a role partially be grounded in disposition?

**Comment by johnbeve** [comment]
How about: _pathogen transporter role_ =def Role borne by a material entity in or on which a pathogen is located, from which the pathogen may be transmitted to a new host. 

I'm trying to avoid the 'capabilities' talk, and refining the definition as much as possible. 

I wouldn't say respiratory droplets have a disposition to transmit for the reasons you mention in the follow-up comment. 

I think the question you end on is worth thinking through. I think in some sense roles must be at least partially grounded in dispositions. A student role is for example partially grounded in the disposition of an agent to consent to being a student, submit work, etc. I think the bearing of the role is externally grounded to the extent that bearing it means the bearer won't necessarily be materially changed without it, so it's - as I understand it - entirely external. Does that make sense?

**Comment by PhiBabs935** [comment]
Yes, everything in the last paragraph sounds right to me. 

I am not sure we should drop all references to dispositions in the definition. Perhaps just change 'capability' to 'disposition'. I have a partly selfish reason, but I think it also has a broader rationale behind it :)  I just spent a bunch of time rewriting part of the IDO paper to emphasize the fact that while mosquitos aren't always bearing a vector role, they always have the ability to transfer pathogens because of abilities deriving from their physical structure. 

I think it is pretty common for scientists to refer to mosquitos as vectors, regardless of whether they are bearing the role in our strict sense. And I think that is part of the reason why Lindsay and others were always weary of whether vectorhood should be a role or disposition. I think that by emphasizing both components we achieve ontological correctness, while also saying something to the intuition that vectorhood is disposition-aly.

**Comment by PhiBabs935** [comment]
I believe that we have addressed all these issues. Though I want us to add an editor's comment to 'pathogen transporter role' making clear that disposition is involved that remains even when the role is not borne. But we can discuss at the call today.
