### ISSUE TITLE
pathogen types

### ISSUE THREAD

**Issue by PhiBabs935** [infectious-disease-ontology-extensions/ido-core#20]
We still need to import to IDO Core terms for fungi, helminth, and protozoa.

**Comment by johnbeve** [comment]
I've made sure fungi is imported from IDO, but I didn't see helminth and protozoa. I think these terms are captured by other terms imported though, e.g. parasite.

**Comment by PhiBabs935** [comment]
Hmm, there is a 'platyhelminths', which IDOSCHISTO imports from NCBITaxon. Although I guess there is a lack of consensus on taxonomy for helminths: https://en.wikipedia.org/wiki/Parasitic_worm#Taxonomy

**Comment by PhiBabs935** [comment]
Was _fungi_ added to IDO Core? I didn't see it in the new IDO-COVID-19 so I wasn't sure. After that we can close this issue I think.

**Comment by johnbeve** [comment]
It should be, but you're right I forgot to include it in the mass owl file.
I'll def add it to the ido file
