### ISSUE TITLE
The use of Disease Ontology definitions for diseases

### ISSUE THREAD

**Issue by PhiBabs935** [infectious-disease-ontology-extensions/ido-core#8]
In the IDO paper, we said that we should use Disease Ontology definitions for diseases. As noted in the paper, the problem here is that DO is notoriously messy in terms of following the OGMS model. 

Werner Ceusters has suggested that instead of trying to get DO to curate their definitions, we should instead create new terms/definitions that are faithful to OGMS. Then we can defend in the paper why we couldn't reuse the DO terms (or will not continue to use them in the case of IDO extensions where we did so already). Hopefully this will force DO to clean up their disease terms. I am inclined to follow W's lead here, but we should probably all chat about this in a call at some point (along with various other issues). 

I think that we should consider going ahead with definitions according to the template provided by IDOSA: Staphylococcus aureus infectious disease =def “Infectious disease that has a staphylococcus aureus infectious disorder as its material basis.” W told me that he thinks this follows OGMS just fine.

Thus, AIDS would be something like: "Infectious disease that has an HIV infectious disorder as its material basis"
Influenza would be something like: "Infectious disease that has an influenza virus infectious disorder as its material basis"
and so on....

**Comment by johnbeve** [comment]
I'm going to close this since it looks like we're going in the OGMS direction, and since and Shane's helpfully spelled out the recipe for logically linking disorder to causative agent.
